DETAILS:
  NAME: VGGish audio
  DISCRIPTION: Demo of using VGGish audio classification to classify audio segments for use in complex event #(TODO: finish this)

TRAINING:
  NUM_PRIMITIVE_EVENTS: 10
  WINDOW_SIZE: 10
  DATASET:
    NAME: UrbanSound8K
    TYPE: audio_wav
    LOCATION: /home/cai/Downloads/datasets/UrbanSound8K

  REASONING:
    LOSS_FUNCTION: MSELoss
    LEARNING_RATE: 0.001 
    EPOCHS: 1000
    
    PARAMETERS:
      DATASET:
        zero_windows: True
        count_windows: False 
        num_workers: 2
        num_data: 1000000
      MODEL:
        hidden_size: 64
        use_relu: False 


  NEUROPLYTORCH: 
    LEARNING_RATE: 0.001
    LOSS_FUNCTION: MSELoss
    EPOCHS: 1000
    
    PARAMETERS:
      DATASET:
        no_test: True
        num_workers: 2
        zero_windows:
          train: True
          val: True
          test: True
        count_windows:
          train: False
          val: False
          test: False


  PERCEPTION:
    MODEL: VGGish
    PRETRAIN:
      MODEL_MODULE: UrbanModel
      DATA_MODULE: UrbanDataModule
      LOSS_FUNCTION: CrossEntropyLoss 
      LEARNING_RATE: 0.001
      PRETRAIN_PERCEPTION: True
      PRETRAIN_EPOCHS: 10
      
    PARAMETERS: 
      DATASET:
        batch_size: 64 
        num_workers: 2
      MODEL:
        input_size: 128


COMPLEX EVENTS:
  COMPLEX EVENT 1: 
    PATTERN: [0,0]
    EVENTS_BETWEEN: [0]
    MAX_TIME: [INF]
  COMPLEX EVENT 2: 
    PATTERN: [1,1]
    EVENTS_BETWEEN: [0]
    MAX_TIME: [INF]
  COMPLEX EVENT 3: 
    PATTERN: [2,2]
    EVENTS_BETWEEN: [0]
    MAX_TIME: [INF]
  COMPLEX EVENT 4: 
    PATTERN: [3,3]
    EVENTS_BETWEEN: [0]
    MAX_TIME: [INF]
  COMPLEX EVENT 5: 
    PATTERN: [4,4]
    EVENTS_BETWEEN: [0]
    MAX_TIME: [INF]
  COMPLEX EVENT 6: 
    PATTERN: [5,5]
    EVENTS_BETWEEN: [0]
    MAX_TIME: [INF]
  COMPLEX EVENT 7: 
    PATTERN: [6,6]
    EVENTS_BETWEEN: [0]
    MAX_TIME: [INF]
  COMPLEX EVENT 8: 
    PATTERN: [7,7]
    EVENTS_BETWEEN: [0]
    MAX_TIME: [INF]
  COMPLEX EVENT 9: 
    PATTERN: [8,8]
    EVENTS_BETWEEN: [0]
    MAX_TIME: [INF]
  COMPLEX EVENT 10: 
    PATTERN: [9,9]
    EVENTS_BETWEEN: [0]
    MAX_TIME: [INF]
  